# The OutisSample Kotlin framework is embedded via the Xcode run-script phase
# (:sample:embedAndSignAppleFrameworkForXcode); CocoaPods is used only to link Mux's iOS Data SDK, which
# the :analytics:mux cinterop binds against. After running `pod install`, open iosApp.xcworkspace.
platform :ios, '15.3'

target 'iosApp' do
  use_frameworks!
  pod 'Mux-Stats-AVPlayer', '~> 4.15'
end
